defaultEntryPoints = ["http", "https"]

[entryPoints]
    [entryPoints.web]
        address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
        to = "websecure"
    [entryPoints.websecure]
        address = ":443"

[api]
    dashboard = true

[providers.docker]
    watch = true
    network = "web"

[providers.file]
    filename = "/etc/traefik/traefik_dynamic.toml"

[log]
# level = '{{env "LOG_LEVEL"}}' # Change to "DEBUG" if you need more informations Doesn't work. 
    format = "common"
    level = "DEBUG"
